export const CATEGORIES = ['낚시', '채집', '요리', '새 사진'];

export const FISH_DATA = [
  { id: 1, name: "민물배스", level: 1, location: ["강"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 2, name: "유럽참개구리", level: 1, location: ["호수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 3, name: "유럽처브", level: 1, location: ["호수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 4, name: "하늘종개", level: 1, location: ["거목강"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 5, name: "바벨", level: 1, location: ["천수강"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 6, name: "큰얼룩배스", level: 1, location: ["노을강"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 7, name: "미노우", level: 1, location: ["고요한 강"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 8, name: "극지연어", level: 1, location: ["온천 산수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 9, name: "붕어", level: 1, location: ["근교 호수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 10, name: "유럽백조어", level: 1, location: ["호수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 11, name: "백조어", level: 1, location: ["근교 호수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 12, name: "왕새우", level: 1, location: ["강"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 13, name: "정어리", level: 1, location: ["바다"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 14, name: "배스", level: 1, location: ["바다"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 15, name: "가다랑어", level: 1, location: ["바다"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 16, name: "갈치", level: 1, location: ["잔잔한 바다"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 17, name: "바다새우", level: 1, location: ["동해"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 18, name: "바다가시고기", level: 2, location: ["구해"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 19, name: "노랑촉수", level: 2, location: ["바다낚시"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 20, name: "돌마자", level: 2, location: ["근교 호수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 21, name: "바다빙어", level: 2, location: ["초원 호수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 22, name: "매화농어", level: 2, location: ["온천 산수"], weather: "맑음", time: [12, 18], image: "" },
  { id: 23, name: "노란전갱이", level: 3, location: ["잔잔한 바다"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 24, name: "해마", level: 3, location: ["고래 바다"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 25, name: "아귀", level: 3, location: ["바다낚시"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 26, name: "홍합", level: 3, location: ["근교 호수"], weather: "비/무지개", time: [0, 6, 12, 18], image: "" },
  { id: 27, name: "민물잰더", level: 3, location: ["거목강"], weather: "맑은 날/무지개", time: [0, 6, 12, 18], image: "" },
  { id: 28, name: "참문어", level: 4, location: ["바다낚시"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 29, name: "대서양난쟁이문어", level: 4, location: ["잔잔한 바다"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 30, name: "망둥어", level: 4, location: ["동해"], weather: "맑음", time: [6, 12], image: "" },
  { id: 31, name: "민물게", level: 4, location: ["근교 호수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 32, name: "대문짝넙치", level: 4, location: ["바다낚시"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 33, name: "유럽가자미", level: 4, location: ["구해"], weather: "맑음", time: [0, 18], image: "" },
  { id: 34, name: "나비잉어", level: 4, location: ["초원 호수"], weather: "비/무지개", time: [0, 6, 12, 18], image: "" },
  { id: 35, name: "송어", level: 5, location: ["초원 호수"], weather: "맑은 날/무지개", time: [0, 18], image: "" },
  { id: 36, name: "유럽날오징어", level: 5, location: ["바다낚시"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 37, name: "대서양은상어", level: 2, location: ["바다"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 38, name: "틸라피아", level: 1, location: ["강"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 39, name: "텐치", level: 1, location: ["숲속 호수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 40, name: "전갱이", level: 1, location: ["고래 바다"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 41, name: "머드개복치", level: 2, location: ["숲속 호수"], weather: "맑음", time: [6, 12, 18], image: "" },
  { id: 42, name: "올챙이", level: 3, location: ["온천 산수"], weather: "비/무지개", time: [0, 6, 12, 18], image: "" },
  { id: 43, name: "유럽민물가재", level: 3, location: ["숲속 호수"], weather: "맑음", time: [0, 6, 18], image: "" },
  { id: 44, name: "대서양연어", level: 4, location: ["고래 바다"], weather: "맑음", time: [0, 12, 18], image: "" },
  { id: 45, name: "소라게", level: 3, location: ["동해"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 46, name: "흰동가리", level: 3, location: ["구해"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 47, name: "큰입배스", level: 4, location: ["숲속 호수"], weather: "맑은 날/무지개", time: [0, 6, 12, 18], image: "" },
  { id: 48, name: "유럽잉어", level: 4, location: ["노을강"], weather: "맑은 날/무지개", time: [12, 18], image: "" },
  { id: 49, name: "민물대구", level: 4, location: ["고요한 강"], weather: "맑음", time: [12, 18], image: "" },
  { id: 50, name: "레드벨리피라냐", level: 4, location: ["거목강"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 51, name: "민물베도라치", level: 5, location: ["노을강"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 52, name: "루드", level: 5, location: ["근교 호수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 53, name: "대서양고등어", level: 5, location: ["고래 바다"], weather: "맑음", time: [12, 18], image: "" },
  { id: 54, name: "유럽가재", level: 5, location: ["잔잔한 바다"], weather: "맑음", time: [0, 18], image: "" },
  { id: 55, name: "큰진주조개", level: 6, location: ["숲속 호수"], weather: "무지개", time: [0, 6, 12, 18], image: "" },
  { id: 56, name: "복어", level: 6, location: ["구해"], weather: "맑음", time: [12, 18], image: "" },
  { id: 57, name: "첨 연어", level: 6, location: ["고요한 강"], weather: "무지개", time: [0, 6, 12, 18], image: "" },
  { id: 58, name: "사루기", level: 6, location: ["근교 호수"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 59, name: "등불성대", level: 6, location: ["동해"], weather: "무지개", time: [0, 6, 12, 18], image: "" },
  { id: 60, name: "두툽상어", level: 6, location: ["바다낚시"], weather: "맑음", time: [0, 6, 12, 18], image: "" },
  { id: 61, name: "큰가시고기", level: 7, location: ["얕은 강"], weather: "비/무지개", time: [0, 6, 12, 18], image: "" },
  { id: 62, name: "졸무늬송사리", level: 7, location: ["근교 호수"], weather: "맑은 날/무지개", time: [0, 12, 18], image: "" },
  { id: 63, name: "둑중개", level: 7, location: ["온천 산수"], weather: "비/무지개", time: [6, 12, 18], image: "" },
  { id: 64, name: "유럽장어", level: 7, location: ["구해"], weather: "무지개", time: [6, 12, 18], image: "" },
  { id: 65, name: "검은점돔", level: 7, location: ["잔잔한 바다"], weather: "비/무지개", time: [0, 18], image: "" },
  { id: 66, name: "산갈치", level: 7, location: ["바다낚시"], weather: "맑음", time: [6, 12], image: "" },
  { id: 67, name: "유럽머드미노우", level: 8, location: ["근교 호수"], weather: "맑은 날/무지개", time: [0, 6], image: "" },
  { id: 68, name: "금붕어", level: 8, location: ["초원 호수"], weather: "비/무지개", time: [6, 12, 18], image: "" },
  { id: 69, name: "블루크로우", level: 8, location: ["숲속 호수"], weather: "맑음", time: [0, 18], image: "" },
  { id: 70, name: "대구", level: 8, location: ["동해"], weather: "맑은 날/무지개", time: [0, 12, 18], image: "" },
  { id: 71, name: "킹크랩", level: 8, location: ["고래 바다"], weather: "무지개", time: [6, 12, 18], image: "" },
  { id: 72, name: "황금킹크랩", level: 8, location: ["바다낚시"], weather: "무지개", time: [0, 6, 12, 18], image: "" },
  { id: 73, name: "후첸", level: 9, location: ["거목강"], weather: "무지개", time: [0, 12, 18], image: "" },
  { id: 74, name: "강꼬치고기", level: 9, location: ["근교 호수"], weather: "비/무지개", time: [0, 18], image: "" },
  { id: 75, name: "펌프킨시드", level: 9, location: ["온천 산수"], weather: "맑은 날/무지개", time: [6, 12, 18], image: "" },
  { id: 76, name: "개복치", level: 9, location: ["동해"], weather: "맑음", time: [0, 6], image: "" },
  { id: 77, name: "참다랑어", level: 9, location: ["잔잔한 바다"], weather: "무지개", time: [6, 12], image: "" },
  { id: 78, name: "달고기/붉평치", level: 9, location: ["바다낚시"], weather: "맑음", time: [0, 18], image: "" },
  { id: 79, name: "유럽메기", level: 10, location: ["초원 호수"], weather: "맑은 날/무지개", time: [0, 18], image: "" },
  { id: 80, name: "블루길", level: 10, location: ["온천 산수"], weather: "맑은 날/무지개", time: [0, 18], image: "" },
  { id: 81, name: "북극곤들매기", level: 10, location: ["숲속 호수"], weather: "비/무지개", time: [12, 18], image: "" },
  { id: 82, name: "귀상어", level: 10, location: ["구해"], weather: "무지개", time: [0, 18], image: "" },
  { id: 83, name: "황새치", level: 10, location: ["고래바다"], weather: "무지개", time: [6, 12], image: "" },
  { id: 84, name: "청상아리", level: 10, location: ["바다낚시"], weather: "무지개", time: [6, 12], image: "" }
];
